-- DATABASE SETUP
DROP DATABASE IF EXISTS squid;
CREATE DATABASE squid
    OWNER = matjaz
    ENCODING = 'UTF8'
    LC_COLLATE = 'it_IT.UTF-8'
    LC_CTYPE = 'it_IT.UTF-8'
    CONNECTION LIMIT = 1000
    TEMPLATE = template0
    ;
